### PR TITLE
Significant performance improvement for sub-images.

### PR DESCRIPTION
**Pull request by mbosecke**
I used JMH to benchmark the throughput of encoding sub-images compared to non-sub-images and I noticed there was a massive difference where sub-images had about _half_ the throughput. Here are the initial results I was seeing:

jmh-results-before-optimizations

I ran an intellij profiler and discovered that `ScanlineProviderFactory` looks for sub-images and makes an entire copy of the image's data in-memory which is not done for non-sub-images. To make matters worse, if a user is following the recommended usage pattern, this will happen twice:

```
PNGWriter writer = new PNGWriter();
if (writer.isScanlineSupported(image)) { // copy of image is done here
     writer.writePNG(bufferedImage, out, 1, FilterType.FILTER_NONE); // another copy of image is done here
}
```

I changed ScanlineProviderFactory to no longer make a copy of the underlying data buffer for sub-images and I changed ScanlineCursor to be smart enough to traverse the underlying data using the raster's translate values. Here are the results I saw after making such a change:

jmh-results-after-optimizations

To accomplish this, the ScanlineCursor needs to be accurately aware of the scanline stride (provided by the raster itself), the pixel stride (provided by the various Provider classes), and the translate X/Y values (provided by the raster), so that it can always keep an accurate position over the underlying data. 

I added a unit test in `PNGWriterBenchmarkTest` that checks if the performance of these two benchmarks are within 10% of each other. It used to fail but it now succeeds. 

I also added more tests to `BufferedImageTypesTest` that compares sub-images for all the different types just to make sure there was better coverage and that this change didn't break any of them.

The motivation behind this change is because I _think_ that the integrated GWC inside of GeoServer uses sub-images in regards to meta-tiling and I hope that this change will propagate to a performance improvement in that project.

### CODE REVIEW

**Comment by mbosecke** [comment]
I should mention that even though my goal was to improve throughput, this obviously has a massive improvement on memory footprint as well since there are no longer multiple copies of the underlying data buffers.

**Comment by mbosecke** [comment]
For clients that are using this PNGWriter, (ex. Geoserver), they will not gain the performance boost if they are still using  [BufferedImageAdapter](https://github.com/geosolutions-it/jai-ext/blob/master/jt-utilities/src/main/java/it/geosolutions/jaiext/BufferedImageAdapter.java) because this adapter was also making a copy of the underlying image data. If they continue to use the adapter, they will generate correct results but slowly, and by removing the adapter, they will see an enormous performance hit on throughput.

I did some preliminary testing and the improvements in Geoserver are measurable and very significant. I'm putting together some detailed data and a pull request for that project but I'm quite optimistic.

**Comment by mbosecke** [comment]
I was able to incorporate this change into GeoServer and found very meaningful results.

https://github.com/geoserver/geoserver/pull/7457

**Comment by aaime** [comment]
Overall this PR looks pretty good. I'm going to wait merging when I can verify that everything works end-to-end (I've reported some issues on the GeoServer side)

**Review by aaime — COMMENTED** [review]
Overall looks good, used it in interactive testing without fail. I'm ok merging this, so that it goes in a future release, but the time spent performance testing should be addressed somehow.

**Comment by aaime** [comment]
Going to add a @ignore on the test for the moment

**Pull request merged**
