### PR TITLE
ClientStreamAbortedException logged at SEVERE level, should be at lower level - merge from 1.1.x

### PR DESCRIPTION
**Pull request by tixvieira**
Removed LOGGER.SEVERE.
Geoserver do the work of logging on Dispatcher.

### CODE REVIEW

**Comment by aaime** [comment]
There are five commits here, the PR should be cleaned up

**Comment by tixvieira** [comment]
I never done that. Can you help with that clean up please? Thanks

**Comment by aaime** [comment]
You basically have to get a 1.2.x clean and up to date checkout, create a new branch off, and cherry-pick the one commit you want.

**Comment by dromagnoli** [comment]
Closed... redone as #187

**Pull request closed without merging**
