### PR TITLE
#58 Support for floating point predictor (type 3) in TIFF Deflate decompressor

### PR DESCRIPTION
**Pull request by kszafran**

### CODE REVIEW

**Comment by dromagnoli** [comment]
Hi @kszafran 
Yep, it looks good to me. Thanks for the contribution. I will merge it.

Just a note: Next time, please, do not reformat a full class (the test one in this example) since that makes hard to find and understand the actual changes. 
I know some classes currently have an ugly indentation. Soon or later we will apply the autoformatting on build as already we have on some other projects :)

Do you have any chance to also backport it on 1.2.x and 1.1.x?

**Comment by kszafran** [comment]
@dromagnoli Sorry for reformatting, I didn't even notice. I must have reformatted it accidentally. I'll correct that and see if I can backport it tomorrow.

**Comment by kszafran** [comment]
File fixed. Turns out it wasn't formatting, it's just that all CRLF line endings were automatically changed to LF.

**Comment by kszafran** [comment]
@dromagnoli I have rebased this PR onto the current master, and also cherry-picked to 1.2.x and 1.1.x:
https://github.com/geosolutions-it/imageio-ext/pull/192
https://github.com/geosolutions-it/imageio-ext/pull/193

**Pull request merged**
